### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.media.models.api_error_py3.ApiError
  - azure.mgmt.media.models.api_error_py3.ApiErrorException
  fullName: azure.mgmt.media.models.api_error_py3
  langs:
  - python
  module: azure.mgmt.media.models.api_error_py3
  name: api_error_py3
  source:
    id: api_error_py3
    path: azure-mgmt-media\azure\mgmt\media\models\api_error_py3.py
    remote:
      branch: master
      path: azure-mgmt-media\azure\mgmt\media\models\api_error_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.media.models.api_error_py3
references:
- fullName: azure.mgmt.media.models.api_error_py3.ApiError
  isExternal: false
  name: ApiError
  parent: azure.mgmt.media.models.api_error_py3
  uid: azure.mgmt.media.models.api_error_py3.ApiError
- fullName: azure.mgmt.media.models.api_error_py3.ApiErrorException
  isExternal: false
  name: ApiErrorException
  parent: azure.mgmt.media.models.api_error_py3
  uid: azure.mgmt.media.models.api_error_py3.ApiErrorException
