### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.servicefabric.models.test_error_chaos_event_py3.TestErrorChaosEvent
  fullName: azure.servicefabric.models.test_error_chaos_event_py3
  langs:
  - python
  module: azure.servicefabric.models.test_error_chaos_event_py3
  name: test_error_chaos_event_py3
  source:
    id: test_error_chaos_event_py3
    path: azure-servicefabric\azure\servicefabric\models\test_error_chaos_event_py3.py
    remote:
      branch: master
      path: azure-servicefabric\azure\servicefabric\models\test_error_chaos_event_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.servicefabric.models.test_error_chaos_event_py3
references:
- fullName: azure.servicefabric.models.test_error_chaos_event_py3.TestErrorChaosEvent
  isExternal: false
  name: TestErrorChaosEvent
  parent: azure.servicefabric.models.test_error_chaos_event_py3
  uid: azure.servicefabric.models.test_error_chaos_event_py3.TestErrorChaosEvent
