### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.servicefabric.models.fabric_error_py3.FabricError
  - azure.servicefabric.models.fabric_error_py3.FabricErrorException
  fullName: azure.servicefabric.models.fabric_error_py3
  langs:
  - python
  module: azure.servicefabric.models.fabric_error_py3
  name: fabric_error_py3
  source:
    id: fabric_error_py3
    path: azure-servicefabric\azure\servicefabric\models\fabric_error_py3.py
    remote:
      branch: master
      path: azure-servicefabric\azure\servicefabric\models\fabric_error_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.servicefabric.models.fabric_error_py3
references:
- fullName: azure.servicefabric.models.fabric_error_py3.FabricError
  isExternal: false
  name: FabricError
  parent: azure.servicefabric.models.fabric_error_py3
  uid: azure.servicefabric.models.fabric_error_py3.FabricError
- fullName: azure.servicefabric.models.fabric_error_py3.FabricErrorException
  isExternal: false
  name: FabricErrorException
  parent: azure.servicefabric.models.fabric_error_py3
  uid: azure.servicefabric.models.fabric_error_py3.FabricErrorException
