### YamlMime:UniversalReference
api_name: []
items:
- fullName: azure.datalake.store.retry.response_from_adal_exception
  langs:
  - python
  module: azure.datalake.store.retry
  name: response_from_adal_exception(e)
  source:
    id: response_from_adal_exception
    path: azure\datalake\store\retry.py
    remote:
      branch: master
      path: azure\datalake\store\retry.py
      repo: https://github.com/Azure/azure-data-lake-store-python
    startLine: 115
  syntax:
    content: response_from_adal_exception(e)
    parameters:
    - id: e
  type: function
  uid: azure.datalake.store.retry.response_from_adal_exception
references: []
