### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.cognitiveservices.vision.face.models.api_error.APIError
  - azure.cognitiveservices.vision.face.models.api_error.APIErrorException
  fullName: azure.cognitiveservices.vision.face.models.api_error
  langs:
  - python
  module: azure.cognitiveservices.vision.face.models.api_error
  name: api_error
  source:
    id: api_error
    path: azure-cognitiveservices-vision-face\azure\cognitiveservices\vision\face\models\api_error.py
    remote:
      branch: master
      path: azure-cognitiveservices-vision-face\azure\cognitiveservices\vision\face\models\api_error.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.cognitiveservices.vision.face.models.api_error
references:
- fullName: azure.cognitiveservices.vision.face.models.api_error.APIError
  isExternal: false
  name: APIError
  parent: azure.cognitiveservices.vision.face.models.api_error
  uid: azure.cognitiveservices.vision.face.models.api_error.APIError
- fullName: azure.cognitiveservices.vision.face.models.api_error.APIErrorException
  isExternal: false
  name: APIErrorException
  parent: azure.cognitiveservices.vision.face.models.api_error
  uid: azure.cognitiveservices.vision.face.models.api_error.APIErrorException
