### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.datafactory.models.managed_integration_runtime_error_py3.ManagedIntegrationRuntimeError
  fullName: azure.mgmt.datafactory.models.managed_integration_runtime_error_py3
  langs:
  - python
  module: azure.mgmt.datafactory.models.managed_integration_runtime_error_py3
  name: managed_integration_runtime_error_py3
  source:
    id: managed_integration_runtime_error_py3
    path: azure-mgmt-datafactory\azure\mgmt\datafactory\models\managed_integration_runtime_error_py3.py
    remote:
      branch: master
      path: azure-mgmt-datafactory\azure\mgmt\datafactory\models\managed_integration_runtime_error_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.datafactory.models.managed_integration_runtime_error_py3
references:
- fullName: azure.mgmt.datafactory.models.managed_integration_runtime_error_py3.ManagedIntegrationRuntimeError
  isExternal: false
  name: ManagedIntegrationRuntimeError
  parent: azure.mgmt.datafactory.models.managed_integration_runtime_error_py3
  uid: azure.mgmt.datafactory.models.managed_integration_runtime_error_py3.ManagedIntegrationRuntimeError
