### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.resource.resources.v2016_09_01.models.resource_management_error_with_details_py3.ResourceManagementErrorWithDetails
  fullName: azure.mgmt.resource.resources.v2016_09_01.models.resource_management_error_with_details_py3
  langs:
  - python
  module: azure.mgmt.resource.resources.v2016_09_01.models.resource_management_error_with_details_py3
  name: resource_management_error_with_details_py3
  source:
    id: resource_management_error_with_details_py3
    path: azure-mgmt-resource\azure\mgmt\resource\resources\v2016_09_01\models\resource_management_error_with_details_py3.py
    remote:
      branch: master
      path: azure-mgmt-resource\azure\mgmt\resource\resources\v2016_09_01\models\resource_management_error_with_details_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.resource.resources.v2016_09_01.models.resource_management_error_with_details_py3
references:
- fullName: azure.mgmt.resource.resources.v2016_09_01.models.resource_management_error_with_details_py3.ResourceManagementErrorWithDetails
  isExternal: false
  name: ResourceManagementErrorWithDetails
  parent: azure.mgmt.resource.resources.v2016_09_01.models.resource_management_error_with_details_py3
  uid: azure.mgmt.resource.resources.v2016_09_01.models.resource_management_error_with_details_py3.ResourceManagementErrorWithDetails
