### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.monitor.models.response_with_error_py3.ResponseWithError
  - azure.mgmt.monitor.models.response_with_error_py3.ResponseWithErrorException
  fullName: azure.mgmt.monitor.models.response_with_error_py3
  langs:
  - python
  module: azure.mgmt.monitor.models.response_with_error_py3
  name: response_with_error_py3
  source:
    id: response_with_error_py3
    path: azure-mgmt-monitor\azure\mgmt\monitor\models\response_with_error_py3.py
    remote:
      branch: master
      path: azure-mgmt-monitor\azure\mgmt\monitor\models\response_with_error_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.monitor.models.response_with_error_py3
references:
- fullName: azure.mgmt.monitor.models.response_with_error_py3.ResponseWithError
  isExternal: false
  name: ResponseWithError
  parent: azure.mgmt.monitor.models.response_with_error_py3
  uid: azure.mgmt.monitor.models.response_with_error_py3.ResponseWithError
- fullName: azure.mgmt.monitor.models.response_with_error_py3.ResponseWithErrorException
  isExternal: false
  name: ResponseWithErrorException
  parent: azure.mgmt.monitor.models.response_with_error_py3
  uid: azure.mgmt.monitor.models.response_with_error_py3.ResponseWithErrorException
