### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.batchai.models.batch_ai_error_py3.BatchAIError
  fullName: azure.mgmt.batchai.models.batch_ai_error_py3
  langs:
  - python
  module: azure.mgmt.batchai.models.batch_ai_error_py3
  name: batch_ai_error_py3
  source:
    id: batch_ai_error_py3
    path: azure-mgmt-batchai\azure\mgmt\batchai\models\batch_ai_error_py3.py
    remote:
      branch: master
      path: azure-mgmt-batchai\azure\mgmt\batchai\models\batch_ai_error_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.batchai.models.batch_ai_error_py3
references:
- fullName: azure.mgmt.batchai.models.batch_ai_error_py3.BatchAIError
  isExternal: false
  name: BatchAIError
  parent: azure.mgmt.batchai.models.batch_ai_error_py3
  uid: azure.mgmt.batchai.models.batch_ai_error_py3.BatchAIError
