### YamlMime:UniversalReference
api_name: []
items:
- children: []
  class: azure.mgmt.resourcegraph.models.facet_error_py3.FacetError
  fullName: azure.mgmt.resourcegraph.models.facet_error_py3.FacetError
  inheritance:
  - inheritance:
    - inheritance:
      - type: builtins.object
      type: msrest.serialization.Model
    type: azure.mgmt.resourcegraph.models.facet_py3.Facet
  langs:
  - python
  module: azure.mgmt.resourcegraph.models.facet_error_py3
  name: FacetError
  source:
    id: FacetError
    path: azure-mgmt-resourcegraph\azure\mgmt\resourcegraph\models\facet_error_py3.py
    remote:
      branch: master
      path: azure-mgmt-resourcegraph\azure\mgmt\resourcegraph\models\facet_error_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 15
  summary: 'A facet whose execution resulted in an error.


    All required parameters must be populated in order to send to Azure.'
  syntax:
    content: 'FacetError(*, expression: str, errors, **kwargs) -> None'
    parameters:
    - description: 'Required. Facet expression, same as in the

        corresponding facet request.'
      id: expression
      type:
      - str
    - description: Required. Constant filled by server.
      id: result_type
      type:
      - str
    - description: 'Required. An array containing detected facet errors with

        details.'
      id: errors
      type:
      - list[azure.mgmt.resourcegraph.models.ErrorDetails]
  type: class
  uid: azure.mgmt.resourcegraph.models.facet_error_py3.FacetError
references:
- fullName: list[azure.mgmt.resourcegraph.models.ErrorDetails]
  name: list[ErrorDetails]
  spec.python:
  - fullName: list
    name: list
    uid: list
  - fullName: '['
    name: '['
  - fullName: azure.mgmt.resourcegraph.models.ErrorDetails
    name: ErrorDetails
    uid: azure.mgmt.resourcegraph.models.ErrorDetails
  - fullName: ']'
    name: ']'
  uid: list[azure.mgmt.resourcegraph.models.ErrorDetails]
