### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.iothub.models.route_error_position_py3.RouteErrorPosition
  fullName: azure.mgmt.iothub.models.route_error_position_py3
  langs:
  - python
  module: azure.mgmt.iothub.models.route_error_position_py3
  name: route_error_position_py3
  source:
    id: route_error_position_py3
    path: azure-mgmt-iothub\azure\mgmt\iothub\models\route_error_position_py3.py
    remote:
      branch: master
      path: azure-mgmt-iothub\azure\mgmt\iothub\models\route_error_position_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.mgmt.iothub.models.route_error_position_py3
references:
- fullName: azure.mgmt.iothub.models.route_error_position_py3.RouteErrorPosition
  isExternal: false
  name: RouteErrorPosition
  parent: azure.mgmt.iothub.models.route_error_position_py3
  uid: azure.mgmt.iothub.models.route_error_position_py3.RouteErrorPosition
