### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.cognitiveservices.vision.customvision.training.models.custom_vision_error_py3.CustomVisionError
  - azure.cognitiveservices.vision.customvision.training.models.custom_vision_error_py3.CustomVisionErrorException
  fullName: azure.cognitiveservices.vision.customvision.training.models.custom_vision_error_py3
  langs:
  - python
  module: azure.cognitiveservices.vision.customvision.training.models.custom_vision_error_py3
  name: custom_vision_error_py3
  source:
    id: custom_vision_error_py3
    path: azure-cognitiveservices-vision-customvision\azure\cognitiveservices\vision\customvision\training\models\custom_vision_error_py3.py
    remote:
      branch: master
      path: azure-cognitiveservices-vision-customvision\azure\cognitiveservices\vision\customvision\training\models\custom_vision_error_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.cognitiveservices.vision.customvision.training.models.custom_vision_error_py3
references:
- fullName: azure.cognitiveservices.vision.customvision.training.models.custom_vision_error_py3.CustomVisionError
  isExternal: false
  name: CustomVisionError
  parent: azure.cognitiveservices.vision.customvision.training.models.custom_vision_error_py3
  uid: azure.cognitiveservices.vision.customvision.training.models.custom_vision_error_py3.CustomVisionError
- fullName: azure.cognitiveservices.vision.customvision.training.models.custom_vision_error_py3.CustomVisionErrorException
  isExternal: false
  name: CustomVisionErrorException
  parent: azure.cognitiveservices.vision.customvision.training.models.custom_vision_error_py3
  uid: azure.cognitiveservices.vision.customvision.training.models.custom_vision_error_py3.CustomVisionErrorException
