### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.batch.custom.custom_errors.CreateTasksErrorException
  fullName: azure.batch.custom.custom_errors
  langs:
  - python
  module: azure.batch.custom.custom_errors
  name: custom_errors
  source:
    id: custom_errors
    path: azure-batch\azure\batch\custom\custom_errors.py
    remote:
      branch: master
      path: azure-batch\azure\batch\custom\custom_errors.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.batch.custom.custom_errors
references:
- fullName: azure.batch.custom.custom_errors.CreateTasksErrorException
  isExternal: false
  name: CreateTasksErrorException
  parent: azure.batch.custom.custom_errors
  uid: azure.batch.custom.custom_errors.CreateTasksErrorException
