### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.batch.models.batch_error_py3.BatchError
  - azure.batch.models.batch_error_py3.BatchErrorException
  fullName: azure.batch.models.batch_error_py3
  langs:
  - python
  module: azure.batch.models.batch_error_py3
  name: batch_error_py3
  source:
    id: batch_error_py3
    path: azure-batch\azure\batch\models\batch_error_py3.py
    remote:
      branch: master
      path: azure-batch\azure\batch\models\batch_error_py3.py
      repo: https://github.com/Azure/azure-sdk-for-python.git
    startLine: 0
  type: module
  uid: azure.batch.models.batch_error_py3
references:
- fullName: azure.batch.models.batch_error_py3.BatchError
  isExternal: false
  name: BatchError
  parent: azure.batch.models.batch_error_py3
  uid: azure.batch.models.batch_error_py3.BatchError
- fullName: azure.batch.models.batch_error_py3.BatchErrorException
  isExternal: false
  name: BatchErrorException
  parent: azure.batch.models.batch_error_py3
  uid: azure.batch.models.batch_error_py3.BatchErrorException
